# Generated by Django 3.2 on 2023-01-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('isOpen', models.BooleanField()),
                ('link', models.TextField()),
                ('tema', models.CharField(blank=True, max_length=100, null=True)),
                ('waktu', models.CharField(blank=True, max_length=100, null=True)),
                ('tempat', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_closing', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
